### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by shoneg** [MattthiasSchedel/bibtex-fetcher#6]
Hi,
this Extension seems to be exacly what I was looking for. Unfortunately, it doesn't work for me. If I click on "Get BibTex", the Ouput shows the following error:

```
2024-10-31 09:23:06.583 [error] [Extension Host] TypeError: Cannot read properties of undefined (reading 'match')
	at t.getBibTexKey (/home/username/.vscode/extensions/matthiasschedel.bibtex-manager-3.6.1/out/extension.js:1:3774)
	at /home/username/.vscode/extensions/matthiasschedel.bibtex-manager-3.6.1/out/extension.js:1:1326
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by MattthiasSchedel** [comment]
Hi Simon, 
Thank you for bringing this to my attention. I will look into it. 

Lets hope scholarAI did not kill their api 🫰
